### PR TITLE
fixed test to have missing headers which indicated a bug that did not exist

### PR DESCRIPTION
**Pull request by adamklifeworks**

### CODE REVIEW

**Review by Clokkehl — APPROVED** [review]

**Comment by gezpage** [comment]
I'm not sure what value the new test adds since it's 99% copypasta of the `test_can_support_requests_lib` test, making the reader play spot the difference between the two. Suggest refactoring the tests to avoid duplication, or removing it entirely if it doesn't add value.

**Comment by dkraczkowski** [comment]
@adamklifeworks Looks good. I would suggest removing this superfluous test.

**Comment by adamklifeworks** [comment]
I've removed the test kept the other updates :)

**Review by Clokkehl — APPROVED** [review]

**Review by gezpage — APPROVED** [review]
Thanks @adamklifeworks 👍

**Pull request merged**
